version: 3.9
services:
  contailner:
    image: docker.io/tailscale/tailscale@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
    privileged: true
    restart: unless-stopped
    hostname: pihole-contailner
    container_name: "pihole-contailner"
    environment:
      # The following 'must not be set' along with a config file
      # according to cmd/containerboot/main.go, otherwise:
      # `tailscale set` and `tailscale up` fail to run
      #- TS_HOSTNAME
      #- TS_ROUTES
      #- TS_ACCEPT_DNS
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR=/custom_config
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ./ts-state:/var/lib/tailscale:rw
      - ./ts-config:/custom_config:Z
      - /dev/net/tun:/dev/net/tun:ro
    cap_add:
      - net_admin
      - sys_module

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole-actual
    hostname: pihole-actual
    image: docker.io/pihole/pihole:latest
    restart: unless-stopped
    # Not necessary for this implementation
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    #  - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'changeme!!'
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole:/etc/pihole:Z
      - ./etc-dnsmasq.d:/etc/dnsmasq.d:Z
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    network_mode: service:contailner
    depends_on:
      - contailner

