services:
  contailner:
    image: docker.io/tailscale/tailscale@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
    privileged: true
    restart: unless-stopped
    container_name: contailner
    hostname: contailner
    environment:
      # The following 'must not be set' along with a config file
      # according to cmd/containerboot/main.go, otherwise:
      # `tailscale set` and `tailscale up` fail to run
      #- TS_HOSTNAME
      #- TS_ROUTES
      #- TS_ACCEPT_DNS
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR=/custom_config
    volumes:
      - ./ts-state:/var/lib/tailscale:rw
      - ./ts-config:/custom_config:Z
      - /dev/net/tun:/dev/net/tun:ro
    cap_add:
      - net_admin
      - sys_module
    # Only necessary if you want these ports to be available on the host
    # By default contailner has full connectivity to 'YOUR-SERVICE'
    #ports: 
    #  - host-port:port-from-services-below

  #YOUR-SERVICE:
  #  ## Any image you choose
  #  image: docker.io/nginx
  #  ## Required for 'contailner' to pass traffic through the tialnet
  #  network_mode: service:contailner
  #  depends_on:
  #    - contailner

