version: 3.9
services:
  contailner:
    image: docker.io/tailscale/tailscale@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
    privileged: true
    restart: unless-stopped
    hostname: traefik-hello-world
    container_name: "traefik-hello-world"
    environment:
      # The following 'must not be set' along with a config file
      # according to cmd/containerboot/main.go, otherwise:
      # `tailscale set` and `tailscale up` fail to run
      #- TS_HOSTNAME
      #- TS_ROUTES
      #- TS_ACCEPT_DNS
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR=/custom_config
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ./state:/var/lib/tailscale:rw
      - ./config:/custom_config:Z
      - /dev/net/tun:/dev/net/tun:ro
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 8000:80    # traefik
      - 8080:8080  # traefik

  traefik:
    image: docker.io/traefik:v3.1.0
    privileged: true
    restart: unless-stopped
    container_name: "traefik"
    network_mode: service:contailner
    depends_on: contailner
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    volumes:
      - /var/run/user/1000/podman/podman.sock:/var/run/docker.sock:rw

    #whoami:
    #  image: docker.io/traefik/whoami
    #  container_name: "simple-service"
    #  network_mode: service:contailner
    #  depends_on: contailner
    #  labels:
    #    - "traefik.enable=true"
    #    - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
    #    - "traefik.http.routers.whoami.entrypoints=web"

